'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require(process.env.AKIM_PLAYWRIGHT_PATH || 'playwright');
const { expect } = require((process.env.AKIM_PLAYWRIGHT_PATH || 'playwright') + '/test');
const { createServer } = require('../server');
(async () => {
  const server = createServer({ env: {} });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  let browser;
  try {
    browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(`http://127.0.0.1:${server.address().port}`);
    await expect(page.locator('#hero-score')).toHaveText('52,56');
    await page.click('#example');
    await expect(page.locator('#hero-score')).toHaveText('56,54');
    assert.equal(await page.locator('#critical').textContent(), '0');
    assert.equal(await page.locator('.recommendation').count(), 3);
    await page.fill('#scenario-name', 'План Нуры');
    await page.click('#save');
    assert.equal(await page.locator('#saved tbody tr').count(), 1);
    await page.click('#explain');
    await expect(page.locator('#briefing')).toContainText('Локальный разбор');
    assert.match(await page.locator('#briefing').textContent(), /56.54/);
    await page.click('[data-question="Что произошло с Нурой?"]');
    await expect(page.locator('#answer')).toContainText('Нура:');
    const downloadEvent = page.waitForEvent('download');
    await page.click('#export');
    const download = await downloadEvent;
    const exported = JSON.parse(fs.readFileSync(await download.path(), 'utf8'));
    assert.equal(exported.choices.length, 5);
    assert.ok(Math.abs(exported.result.score - 56.54307) < 1e-9);
    await page.click('[data-apply="0"]');
    await expect(page.locator('#hero-score')).toHaveText('57,21');
    await page.reload();
    await page.waitForSelector('#saved [data-load="0"]');
    await page.click('#saved [data-load="0"]');
    await expect(page.locator('#hero-score')).toHaveText('56,54');
    const output = path.join(__dirname, '..', 'docs');
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: path.join(output, 'preview-desktop.png') });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: path.join(output, 'preview-mobile.png') });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'horizontal overflow on mobile');
    await page.setViewportSize({ width: 1440, height: 1100 });
    await page.click('#clear');
    await expect(page.locator('#decision-count')).toContainText('0 / 5');
    await page.click('[data-add="M1"]');
    await expect(page.locator('#decision-count')).toContainText('1 / 5');
    assert.equal(await page.locator('[data-add="M1"]').isDisabled(), true);
    await page.click('[data-add="M3"]');
    await expect(page.locator('#notice')).toContainText('несовместимы');
    assert.ok((await page.locator('#decision-count').textContent()).startsWith('1'));
    await page.click('[data-filter="Сервисы"]');
    assert.equal(await page.locator('.measure').count(), 3);
    assert.deepEqual(errors, []);
    console.log('Browser smoke passed: initial/example scores, save/reload, offline briefing, export, recommendation, conflict, category filter, mobile overflow.');
  } finally {
    if (browser) await browser.close();
    server.closeAllConnections();
    await new Promise(resolve => server.close(resolve));
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
