'use strict';
const $=id=>document.getElementById(id), choices=[],saved=[];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>n.toFixed(2);
$('measure').innerHTML=measures.map(m=>`<option value="${m.id}">${m.id} · ${esc(m.name)} — ${m.cost}</option>`).join('');
$('district').innerHTML=districts.map(d=>`<option>${esc(d.name)}</option>`).join('');
function updateSelect(){const m=byId[$('measure').value];$('district').disabled=m.type==='Город';$('details').textContent=`${m.category} · ${m.type} · лаг ${m.lag} кв. · эффекты: ${Object.entries(m.effects).map(([k,v])=>`${k} ${v>0?'+':''}${v}`).join(', ')}`}
$('measure').onchange=updateSelect;updateSelect();
function render(){const cost=choices.reduce((s,c)=>s+byId[c.id].cost,0);$('picked').innerHTML=choices.map((c,i)=>`<div class="row"><span>${esc(c.id)} · ${esc(byId[c.id].name)} <small class="muted">${esc(c.district||'Город')}</small></span><button data-remove="${i}" aria-label="Удалить">×</button></div>`).join('');
 $('picked').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{choices.splice(Number(b.dataset.remove),1);render()});$('budget').textContent=`Потрачено ${cost}/100 · осталось ${100-cost} · решений ${choices.length}/5`;$('budgetbar').style.width=`${Math.min(cost,100)}%`;
 const errors=validate(choices,false);$('status').className=errors.length?'error':'good';$('status').textContent=errors.length?errors.join(' '):choices.length===5?'Сценарий допустим.':'Добавьте решения до пяти.';
 if(choices.length!==5||errors.length){$('result').innerHTML='<p>Итог появится после пяти допустимых решений.</p>';$('districts').innerHTML='';return}
 const r=calculate(choices),change=r.score-baseline.score,weak=r.rows.reduce((a,b)=>a.score<b.score?a:b);$('result').innerHTML=`<div class="big">${fmt(r.score)}</div><p class="good">${change>=0?'+':''}${fmt(change)} к базе ${fmt(baseline.score)}</p><div class="cols"><div>Средний балл<br><strong>${fmt(r.average)}</strong></div><div>Слабейший район<br><strong>${esc(weak.name)} · ${fmt(weak.score)}</strong></div><div>Критических значений<br><strong>${r.critical.length}</strong></div></div><h3>Объяснение</h3><p>Средневзвешенный показатель города вырос на ${fmt(r.average-baseline.average)}. Самый слабый район — ${esc(weak.name)}; его результат влияет на 30% формулы. ${r.critical.length?`Остаются критические показатели: ${esc(r.critical.join(', '))}. Штраф: ${r.critical.length}.`:'Критических показателей ниже 40 не осталось.'} Бюджетный остаток ${100-r.cost} баллов не прибавляет.</p><h3>Вклад мер в показатели</h3><div class="scroll"><table><tr><th>Мера</th><th>Район</th><th>Показатель</th><th>Изменение</th></tr>${r.contributions.map(c=>`<tr><td>${esc(c.source)}</td><td>${esc(c.district)}</td><td>${esc(c.indicator)}</td><td>${c.delta>0?'+':''}${fmt(c.delta)}</td></tr>`).join('')}</table></div>`;
 $('districts').innerHTML=`<table><tr><th>Район</th><th>Было</th><th>Стало</th><th>Изменение</th>${K.map(k=>`<th>${k}</th>`).join('')}</tr>${r.rows.map(row=>`<tr><td>${esc(row.name)}</td><td>${fmt(row.baseline)}</td><td>${fmt(row.score)}</td><td>${fmt(row.score-row.baseline)}</td>${row.indicators.map(v=>`<td class="${v<40?'error':''}">${fmt(v)}</td>`).join('')}</tr>`).join('')}</table>`;
}
$('add').onclick=()=>{const m=byId[$('measure').value],next=[...choices,{id:m.id,district:m.type==='Город'?null:$('district').value}],errors=validate(next,false);if(errors.length){$('status').className='error';$('status').textContent=errors.join(' ');return}choices.push(next.at(-1));render()};
$('clear').onclick=()=>{choices.splice(0);render()};
$('example').onclick=()=>{choices.splice(0,choices.length,...[['M7','Нура'],['M8','Нура'],['M10','Нура'],['M12',null],['M5','Сарыарка']].map(([id,district])=>({id,district})));render()};
$('cheap').onclick=()=>{choices.splice(0,choices.length,...[['M9','Нура'],['M11','Нура'],['M10','Нура'],['M12',null],['M4','Сарыарка']].map(([id,district])=>({id,district})));render()};
$('save').onclick=()=>{const r=calculate(choices);if(!r.valid){$('status').className='error';$('status').textContent=r.errors.join(' ');return}saved.push({score:r.score,cost:r.cost,choices:choices.map(c=>({...c}))});$('saved').innerHTML=saved.map((s,i)=>`<div class="row"><span>Сценарий ${i+1}: <strong>${fmt(s.score)}</strong> · стоимость ${s.cost}</span><button data-load="${i}">Открыть</button></div>`).join('');$('saved').querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{choices.splice(0,choices.length,...saved[Number(b.dataset.load)].choices.map(c=>({...c})));render()})};render();
