const assert=require('node:assert/strict');const {calculate,baseline,validate}=require('./engine');
const example=[['M7','Нура'],['M8','Нура'],['M10','Нура'],['M12',null],['M5','Сарыарка']].map(([id,district])=>({id,district}));
const r=calculate(example);assert.equal(r.valid,true);assert.equal(r.cost,95);assert.equal(baseline.critical,2);
assert.ok(Math.abs(baseline.score-52.56)<.02);assert.ok(r.score>baseline.score);
assert.ok(r.contributions.some(c=>c.source==='M10+M12'&&c.district==='Нура'&&c.delta===2));
assert.ok(validate(example.slice(0,4)).length);assert.ok(validate([...example,{id:'M9',district:'Нура'}]).length);
assert.ok(validate([{id:'M1',district:'Нура'},{id:'M3',district:'Есиль'}],false).length);
assert.ok(validate([{id:'M4',district:'Нура'},{id:'M7',district:'Нура'}],false).length);
assert.equal(validate([{id:'M4',district:'Есиль'},{id:'M7',district:'Нура'}],false).length,0);
assert.ok(validate([{id:'M1',district:null}],false).length);
assert.ok(validate([{id:'M12',district:'Нура'}],false).length);
console.log({baseline:baseline.score,example:r.score,delta:r.score-baseline.score});
